name: frontend_sync_d
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Design ---
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  cupertino_icons: ^1.0.6

  # --- State Management ---
  provider: ^6.1.2

  # --- Networking & Auth ---
  http: ^1.2.0  # Stable version for compatibility
  stomp_dart_client: ^1.0.0 # Keeping 1.0.0 as used in your SocketService code
  shared_preferences: ^2.2.0

  # --- Device Features ---
  installed_apps: ^1.0.0 # For Game Library Scanning (Fixed namespace issue)
  permission_handler: ^11.3.0 # For requesting camera/mic permissions
  screen_brightness: ^2.0.0 # For keeping screen on during gaming

  # --- Video / WebRTC ---
  flutter_webrtc: ^0.12.3 # Essential for screen mirroring

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/

  fonts:
    - family: Pixer
      fonts:
        - asset: assets/font/Pixer-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon_padded.png"

flutter_native_splash:
  color: "#1B1717"